version: '3.8'

services:
  frontend:
    build: ./employee-front
    ports:
      - '80:80'

  api:
    build: ./employee-api
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    build: ./employee-database
    environment:
      SA_PASSWORD: "SqlServer2023*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
