USE company;
GO

CREATE TABLE Role (
  Id UNIQUEIDENTIFIER PRIMARY KEY,
  Description VARCHAR(250) NOT NULL,
  Department VARCHAR(250) NOT NULL
);

CREATE TABLE Employee (
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  FirstName VARCHAR(250) NOT NULL,
  LastName VARCHAR(250) NOT NULL,
  BirthDate DATE NOT NULL,
  Gender TINYINT NOT NULL,
  Role UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Role(Id)
);
GO
